name: Deploy mdBook

on:
  push:
    branches:
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.14'
      
      - name: Build mdBook
        run: |
          cd ./typestate-book/
          mdbook build

      - name: Deploy mdBook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./typestate-book/book